### NUMPY

In [1]:
import numpy as np

In [3]:
np.__version__

'1.19.5'

In [4]:
np.array([1,2,3,4,5])

array([1, 2, 3, 4, 5])

In [5]:
# array as opposed to list will only contain a single data type
# in the below error, it will typecast all elements as string

np.array([1,2,3,False,True,'abcd','sumi'])

array(['1', '2', '3', 'False', 'True', 'abcd', 'sumi'], dtype='<U21')

In [6]:
# applying basic math operations to list vs array

sample_list = [1,2,3,4]
sample_list * 2

[1, 2, 3, 4, 1, 2, 3, 4]

In [8]:
np.array(sample_list) * 2

array([2, 4, 6, 8])

#### Matrix
* numpy helps with linear algebra
* matrix is a basic structure for linear algebra

In [9]:
a = [[1,2,3], [4,5,6], [7,8,9]] # nested list
mtrx = np.array(a)
mtrx

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [11]:
mtrx[2]

array([7, 8, 9])

In [14]:
mtrx[2][1] # indexing is row number first then column number

8

In [32]:
mtrx[0:2] # using colon indexing results in a sub array

array([[1, 2, 3],
       [4, 5, 6]])

In [38]:
mtrx[0:]

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [39]:
# number of initial square brackets shows the n dimensionality of the array

In [ ]:
# shape declared as a tuple - (rows, columns)

In [40]:
np.random.randint(0, 10, (3, 3))

array([[3, 5, 8],
       [5, 1, 9],
       [6, 5, 9]])

In [42]:
np.random.randn(3,4) # random numbers in the dimension, with a normal distribution

array([[-0.02695553, -0.81308511,  0.56763498, -0.83236591],
       [ 1.09784252,  1.0683096 ,  0.22937012, -0.23205363],
       [ 1.09657761,  1.87898148,  0.79519493, -1.00757275]])

In [44]:
np.ones([5, 12])

array([[1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.]])

In [47]:
# fixing random behavior to generate same random numbers
# here because the seed is set, this cell will generate the same random numbers

np.random.seed(2)
np.random.randint(2,23, (5, 6))

array([[10, 17, 15, 10, 13, 20],
       [13, 10,  9,  4, 19, 13],
       [17, 22, 22,  7,  9,  5],
       [ 8,  6, 12, 13, 21,  9],
       [ 8, 12,  3,  5,  7,  6]])

In [48]:
np.zeros((3,4), dtype = int)

array([[0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0]])

In [49]:
# creating an identity matrix
# identity matrices are square matrices hence a single arguement in the function

np.identity(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [52]:
np.identity(10, dtype = int)

array([[1, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 1, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 1, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 1, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 1, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 1, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 1, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 1, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 1, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 1]])

In [53]:
np.full((3, 5), 3.14)

array([[3.14, 3.14, 3.14, 3.14, 3.14],
       [3.14, 3.14, 3.14, 3.14, 3.14],
       [3.14, 3.14, 3.14, 3.14, 3.14]])

In [54]:
# axis = 0 <- rows... axis = 1 <- columns

In [60]:
zero_m = np.zeros((3,5), dtype=int)
one_m = np.ones((3,5), dtype=int)

In [61]:
combined_m = np.concatenate([zero_m, one_m], axis=0)

In [62]:
combined_m

array([[0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]])

In [63]:
combined_m_2 = np.concatenate([zero_m, one_m], axis=1)

In [64]:
combined_m_2

array([[0, 0, 0, 0, 0, 1, 1, 1, 1, 1],
       [0, 0, 0, 0, 0, 1, 1, 1, 1, 1],
       [0, 0, 0, 0, 0, 1, 1, 1, 1, 1]])

In [65]:
np.zeros_like(combined_m)

array([[0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0]])

### SCIPY

In [1]:
import scipy

In [2]:
scipy.__version__

'1.6.1'

In [3]:
# !pip install scipy = 1.4.1

In [4]:
from scipy.misc import derivative

In [5]:
def my_function(x):
    return x**2 + x + 1

derivative(my_function, x0=2)

5.0

In [6]:
# comb - combination, perm - permutation

In [7]:
from scipy import linalg

In [9]:
import numpy as np

In [10]:
np.arange(2,19,2)

array([ 2,  4,  6,  8, 10, 12, 14, 16, 18])

In [16]:
mat = np.random.randint(2, 19, (4,4))

In [17]:
# determinant of the matrix

linalg.det(mat)

3087.9999999999986

In [18]:
linalg.inv(mat)

array([[-0.01262953, -0.2244171 ,  0.38115285, -0.13180052],
       [ 0.13795337,  0.06670984, -0.24028497,  0.05505181],
       [-0.02072539,  0.09326425, -0.01554404, -0.0880829 ],
       [-0.00680052,  0.18685233, -0.33322539,  0.2367228 ]])

### OS

In [19]:
import os

In [21]:
new_txt_file = open('new_txt_file.txt', 'w+')

In [23]:
l1 = 'Noor is the prettiest thing in the world!'
l2 = 'God bless Everyone'
l3 = 'Waherguru'


new_txt_file.writelines([l1, l2, l3])

In [24]:
new_txt_file.seek(0)
print(new_txt_file.read())

Noor is the prettiest thing in the world!God bless EveryoneWaherguru


In [25]:
new_txt_file.close()

In [34]:
with open('new_txt_file.txt', 'r') as f:
    print(f.read())

Noor is the prettiest thing in the world!God bless EveryoneWaherguru


In [35]:
from scipy.misc import derivative

In [36]:
def my_func(x):
    return x**2 + 5

derivative(my_func, x0=2)

4.0

### PANDAS

In [14]:
import pandas as pd
pd.options.display.max_columns = 100
pd.options.display.float_format = '{:,.2f}'.format

In [15]:
pd.__version__

'1.2.3'

In [16]:
df = pd.read_csv('big_mart_sales.csv')

In [17]:
df.head(20)

Item_Identifier 
 Item_Weight 
 Item_Fat_Content 
 Item_Visibility 
 Item_Type 
 Item_MRP 
 Outlet_Identifier 
 Outlet_Establishment_Year 
 Outlet_Size 
 Outlet_Location_Type 
 Outlet_Type 
 Item_Outlet_Sales 
 
 
 
 
 0 
 FDA15 
 9.30 
 Low Fat 
 0.02 
 Dairy 
 249.81 
 OUT049 
 1999 
 Medium 
 Tier 1 
 Supermarket Type1 
 3,735.14 
 
 
 1 
 DRC01 
 5.92 
 Regular 
 0.02 
 Soft Drinks 
 48.27 
 OUT018 
 2009 
 Medium 
 Tier 3 
 Supermarket Type2 
 443.42 
 
 
 2 
 FDN15 
 17.50 
 Low Fat 
 0.02 
 Meat 
 141.62 
 OUT049 
 1999 
 Medium 
 Tier 1 
 Supermarket Type1 
 2,097.27 
 
 
 3 
 FDX07 
 19.20 
 Regular 
 0.00 
 Fruits and Vegetables 
 182.09 
 OUT010 
 1998 
 NaN 
 Tier 3 
 Grocery Store 
 732.38 
 
 
 4 
 NCD19 
 8.93 
 Low Fat 
 0.00 
 Household 
 53.86 
 OUT013 
 1987 
 High 
 Tier 3 
 Supermarket Type1 
 994.71 
 
 
 5 
 FDP36 
 10.39 
 Regular 
 0.00 
 Baking Goods 
 51.40 
 OUT018 
 2009 
 Medium 
 Tier 3 
 Supermarket Type2 
 556.61 
 
 
 6 
 FDO10 
 13.65 
 Regular 
 0.01 
 Snack Foods 
 57.66 
 OUT013 
 1987 
 High 
 Tier 3 
 Supermarket Type1 
 343.55 
 
 
 7 
 FDP10 
 NaN 
 Low Fat 
 0.13 
 Snack Foods 
 107.76 
 OUT027 
 1985 
 Medium 
 Tier 3 
 Supermarket Type3 
 4,022.76 
 
 
 8 
 FDH17 
 16.20 
 Regular 
 0.02 
 Frozen Foods 
 96.97 
 OUT045 
 2002 
 NaN 
 Tier 2 
 Supermarket Type1 
 1,076.60 
 
 
 9 
 FDU28 
 19.20 
 Regular 
 0.09 
 Frozen Foods 
 187.82 
 OUT017 
 2007 
 NaN 
 Tier 2 
 Supermarket Type1 
 4,710.53 
 
 
 10 
 FDY07 
 11.80 
 Low Fat 
 0.00 
 Fruits and Vegetables 
 45.54 
 OUT049 
 1999 
 Medium 
 Tier 1 
 Supermarket Type1 
 1,516.03 
 
 
 11 
 FDA03 
 18.50 
 Regular 
 0.05 
 Dairy 
 144.11 
 OUT046 
 1997 
 Small 
 Tier 1 
 Supermarket Type1 
 2,187.15 
 
 
 12 
 FDX32 
 15.10 
 Regular 
 0.10 
 Fruits and Vegetables 
 145.48 
 OUT049 
 1999 
 Medium 
 Tier 1 
 Supermarket Type1 
 1,589.26 
 
 
 13 
 FDS46 
 17.60 
 Regular 
 0.05 
 Snack Foods 
 119.68 
 OUT046 
 1997 
 Small 
 Tier 1 
 Supermarket Type1 
 2,145.21 
 
 
 14 
 FDF32 
 16.35 
 Low Fat 
 0.07 
 Fruits and Vegetables 
 196.44 
 OUT013 
 1987 
 High 
 Tier 3 
 Supermarket Type1 
 1,977.43 
 
 
 15 
 FDP49 
 9.00 
 Regular 
 0.07 
 Breakfast 
 56.36 
 OUT046 
 1997 
 Small 
 Tier 1 
 Supermarket Type1 
 1,547.32 
 
 
 16 
 NCB42 
 11.80 
 Low Fat 
 0.01 
 Health and Hygiene 
 115.35 
 OUT018 
 2009 
 Medium 
 Tier 3 
 Supermarket Type2 
 1,621.89 
 
 
 17 
 FDP49 
 9.00 
 Regular 
 0.07 
 Breakfast 
 54.36 
 OUT049 
 1999 
 Medium 
 Tier 1 
 Supermarket Type1 
 718.40 
 
 
 18 
 DRI11 
 NaN 
 Low Fat 
 0.03 
 Hard Drinks 
 113.28 
 OUT027 
 1985 
 Medium 
 Tier 3 
 Supermarket Type3 
 2,303.67 
 
 
 19 
 FDU02 
 13.35 
 Low Fat 
 0.10 
 Dairy 
 230.54 
 OUT035 
 2004 
 Small 
 Tier 2 
 Supermarket Type1 
 2,748.42

In [18]:
df.shape

(8523, 12)

In [19]:
df.columns

Index(['Item_Identifier', 'Item_Weight', 'Item_Fat_Content', 'Item_Visibility',
       'Item_Type', 'Item_MRP', 'Outlet_Identifier',
       'Outlet_Establishment_Year', 'Outlet_Size', 'Outlet_Location_Type',
       'Outlet_Type', 'Item_Outlet_Sales'],
      dtype='object')

In [20]:
df.dtypes

Item_Identifier               object
Item_Weight                  float64
Item_Fat_Content              object
Item_Visibility              float64
Item_Type                     object
Item_MRP                     float64
Outlet_Identifier             object
Outlet_Establishment_Year      int64
Outlet_Size                   object
Outlet_Location_Type          object
Outlet_Type                   object
Item_Outlet_Sales            float64
dtype: object

In [21]:
df.isnull().sum()

Item_Identifier                 0
Item_Weight                  1463
Item_Fat_Content                0
Item_Visibility                 0
Item_Type                       0
Item_MRP                        0
Outlet_Identifier               0
Outlet_Establishment_Year       0
Outlet_Size                  2410
Outlet_Location_Type            0
Outlet_Type                     0
Item_Outlet_Sales               0
dtype: int64

In [22]:
df.describe()

Item_Weight 
 Item_Visibility 
 Item_MRP 
 Outlet_Establishment_Year 
 Item_Outlet_Sales 
 
 
 
 
 count 
 7,060.00 
 8,523.00 
 8,523.00 
 8,523.00 
 8,523.00 
 
 
 mean 
 12.86 
 0.07 
 140.99 
 1,997.83 
 2,181.29 
 
 
 std 
 4.64 
 0.05 
 62.28 
 8.37 
 1,706.50 
 
 
 min 
 4.55 
 0.00 
 31.29 
 1,985.00 
 33.29 
 
 
 25% 
 8.77 
 0.03 
 93.83 
 1,987.00 
 834.25 
 
 
 50% 
 12.60 
 0.05 
 143.01 
 1,999.00 
 1,794.33 
 
 
 75% 
 16.85 
 0.09 
 185.64 
 2,004.00 
 3,101.30 
 
 
 max 
 21.35 
 0.33 
 266.89 
 2,009.00 
 13,086.96

In [23]:
df.describe(include = 'all')

Item_Identifier 
 Item_Weight 
 Item_Fat_Content 
 Item_Visibility 
 Item_Type 
 Item_MRP 
 Outlet_Identifier 
 Outlet_Establishment_Year 
 Outlet_Size 
 Outlet_Location_Type 
 Outlet_Type 
 Item_Outlet_Sales 
 
 
 
 
 count 
 8523 
 7,060.00 
 8523 
 8,523.00 
 8523 
 8,523.00 
 8523 
 8,523.00 
 6113 
 8523 
 8523 
 8,523.00 
 
 
 unique 
 1559 
 NaN 
 5 
 NaN 
 16 
 NaN 
 10 
 NaN 
 3 
 3 
 4 
 NaN 
 
 
 top 
 FDW13 
 NaN 
 Low Fat 
 NaN 
 Fruits and Vegetables 
 NaN 
 OUT027 
 NaN 
 Medium 
 Tier 3 
 Supermarket Type1 
 NaN 
 
 
 freq 
 10 
 NaN 
 5089 
 NaN 
 1232 
 NaN 
 935 
 NaN 
 2793 
 3350 
 5577 
 NaN 
 
 
 mean 
 NaN 
 12.86 
 NaN 
 0.07 
 NaN 
 140.99 
 NaN 
 1,997.83 
 NaN 
 NaN 
 NaN 
 2,181.29 
 
 
 std 
 NaN 
 4.64 
 NaN 
 0.05 
 NaN 
 62.28 
 NaN 
 8.37 
 NaN 
 NaN 
 NaN 
 1,706.50 
 
 
 min 
 NaN 
 4.55 
 NaN 
 0.00 
 NaN 
 31.29 
 NaN 
 1,985.00 
 NaN 
 NaN 
 NaN 
 33.29 
 
 
 25% 
 NaN 
 8.77 
 NaN 
 0.03 
 NaN 
 93.83 
 NaN 
 1,987.00 
 NaN 
 NaN 
 NaN 
 834.25 
 
 
 50% 
 NaN 
 12.60 
 NaN 
 0.05 
 NaN 
 143.01 
 NaN 
 1,999.00 
 NaN 
 NaN 
 NaN 
 1,794.33 
 
 
 75% 
 NaN 
 16.85 
 NaN 
 0.09 
 NaN 
 185.64 
 NaN 
 2,004.00 
 NaN 
 NaN 
 NaN 
 3,101.30 
 
 
 max 
 NaN 
 21.35 
 NaN 
 0.33 
 NaN 
 266.89 
 NaN 
 2,009.00 
 NaN 
 NaN 
 NaN 
 13,086.96

In [24]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 8523 entries, 0 to 8522
Data columns (total 12 columns):
 #   Column                     Non-Null Count  Dtype  
---  ------                     --------------  -----  
 0   Item_Identifier            8523 non-null   object 
 1   Item_Weight                7060 non-null   float64
 2   Item_Fat_Content           8523 non-null   object 
 3   Item_Visibility            8523 non-null   float64
 4   Item_Type                  8523 non-null   object 
 5   Item_MRP                   8523 non-null   float64
 6   Outlet_Identifier          8523 non-null   object 
 7   Outlet_Establishment_Year  8523 non-null   int64  
 8   Outlet_Size                6113 non-null   object 
 9   Outlet_Location_Type       8523 non-null   object 
 10  Outlet_Type                8523 non-null   object 
 11  Item_Outlet_Sales          8523 non-null   float64
dtypes: float64(4), int64(1), object(7)
memory usage: 799.2+ KB


### MATPLOTLIB

In [25]:
import matplotlib

In [26]:
matplotlib.__version__

'3.3.4'

In [27]:
import matplotlib.pyplot as plt
import numpy as np
import pandas as pd
%matplotlib inline

In [30]:
#line plot
x = np.linspace(0,10,1000)

plt.plot(x, np.cos(x), label='cosine')

In [37]:
data = pd.DataFrame(
                    [[1,2,3],
                    [4,5,6],
                    [7,8,9]]
)

In [38]:
data

0 
 1 
 2 
 
 
 
 
 0 
 1 
 2 
 3 
 
 
 1 
 4 
 5 
 6 
 
 
 2 
 7 
 8 
 9

In [39]:
data.plot(kind = 'bar', stacked = True)

<AxesSubplot:>