1. Write a Python program to sum all the items in a list.

In [3]:
lst_1 = [1,2,3,4,5]

In [4]:
def sum_list(lst):
    plus = 0
    for i in lst:
        plus += i
    print(plus)

sum_list(lst_1)

15


2. Write a Python program to multiplies all the items in a list.

In [6]:
def of_list(lst):
    of = 1
    for i in lst:
        of *= i
    print (of)

of_list(lst_1)

120


3. Write a Python program to get the largest number from a list.

In [12]:
def maxinlist(lst):
    maximum = lst[0]
    for i in lst:
        if i > maximum:
            maximum = i
    print(maximum)

maxinlist(lst_1)

5


4. Write a Python program to get the smallest number from a list.

In [14]:
def mininlist(lst):
    minimum = lst[0]
    for i in lst:
        if i < minimum:
            minimum = i
    print(minimum)

mininlist(lst_1)

1


5. Write a Python program to count the number of strings where the string length is 2 or more and the first 
and last character are same from a given list of strings.
Sample List : ['abc', 'xyz', 'aba', '1221']
Expected Result : 2

In [18]:
def counter(words):
    cnt = 0    
    for word in words:
        if len(word) >= 2 and word[0] == word[-1]:
            cnt += 1
    print(cnt)

lst_w = ["Sumis", "SammS", "PiP"]

counter(lst_w)

2


In [19]:
new_lst = lst_w.copy()

In [20]:
new_lst

['Sumis', 'SammS', 'PiP']

In [21]:
new_list2 = list(lst_1)

In [22]:
new_list2

[1, 2, 3, 4, 5]

12. Write a Python program to print a specified list after removing the 0th, 4th and 5th elements. Go to the editor
Sample List : ['Red', 'Green', 'White', 'Black', 'Pink', 'Yellow']
Expected Output : ['Green', 'White', 'Black']

In [37]:
z = [o for i, o in enumerate(x) if i != 0 and i != 4 and i != 5]

In [38]:
z

['Green', 'White', 'Black']

In [39]:
z = [o for i, o in enumerate(x) if i not in (0,4,5)]

In [40]:
z

['Green', 'White', 'Black']

In [41]:
x = ['Red', 'Green', 'White', 'Black', 'Pink', 'Yellow']
y = x[1:4]
y

['Green', 'White', 'Black']

Write a Python program to generate a 3*4*6 3D array whose each element is *.

In [42]:
dim_3d = [[['*' for col in range(4)] for col in range(6)]for col in range(3)]

In [43]:
dim_3d

[[['*', '*', '*', '*'],
  ['*', '*', '*', '*'],
  ['*', '*', '*', '*'],
  ['*', '*', '*', '*'],
  ['*', '*', '*', '*'],
  ['*', '*', '*', '*']],
 [['*', '*', '*', '*'],
  ['*', '*', '*', '*'],
  ['*', '*', '*', '*'],
  ['*', '*', '*', '*'],
  ['*', '*', '*', '*'],
  ['*', '*', '*', '*']],
 [['*', '*', '*', '*'],
  ['*', '*', '*', '*'],
  ['*', '*', '*', '*'],
  ['*', '*', '*', '*'],
  ['*', '*', '*', '*'],
  ['*', '*', '*', '*']]]

In [44]:
dim_4d = [[[['*' for col in range(4)] for col in range(6)]for col in range(3)]for col in range(2)]

In [45]:
dim_4d

[[[['*', '*', '*', '*'],
   ['*', '*', '*', '*'],
   ['*', '*', '*', '*'],
   ['*', '*', '*', '*'],
   ['*', '*', '*', '*'],
   ['*', '*', '*', '*']],
  [['*', '*', '*', '*'],
   ['*', '*', '*', '*'],
   ['*', '*', '*', '*'],
   ['*', '*', '*', '*'],
   ['*', '*', '*', '*'],
   ['*', '*', '*', '*']],
  [['*', '*', '*', '*'],
   ['*', '*', '*', '*'],
   ['*', '*', '*', '*'],
   ['*', '*', '*', '*'],
   ['*', '*', '*', '*'],
   ['*', '*', '*', '*']]],
 [[['*', '*', '*', '*'],
   ['*', '*', '*', '*'],
   ['*', '*', '*', '*'],
   ['*', '*', '*', '*'],
   ['*', '*', '*', '*'],
   ['*', '*', '*', '*']],
  [['*', '*', '*', '*'],
   ['*', '*', '*', '*'],
   ['*', '*', '*', '*'],
   ['*', '*', '*', '*'],
   ['*', '*', '*', '*'],
   ['*', '*', '*', '*']],
  [['*', '*', '*', '*'],
   ['*', '*', '*', '*'],
   ['*', '*', '*', '*'],
   ['*', '*', '*', '*'],
   ['*', '*', '*', '*'],
   ['*', '*', '*', '*']]]]

In [46]:
import operator

In [48]:
operator.itemgetter(lst_1)

operator.itemgetter([1, 2, 3, 4, 5])

In [53]:
sett = {1,2,2,2,2,4,4,5,6,7,8}

In [54]:
sett

{1, 2, 4, 5, 6, 7, 8}

In [55]:
sett.add("Avengers")

In [56]:
sett

{1, 2, 4, 5, 6, 7, 8, 'Avengers'}

In [2]:
my_list = [1,2,3,4,5]

In [3]:
import numpy as np
arr = np.array(my_list)

In [4]:
arr

array([1, 2, 3, 4, 5])

In [6]:
arr.shape

(5,)

In [9]:
my_lst1=[1,2,3,4,5]
my_lst2=[2,3,4,5,6]
my_lst3=[9,7,6,8,9]
arr = np.array([my_lst1,my_lst2,my_lst3])
arr

array([[1, 2, 3, 4, 5],
       [2, 3, 4, 5, 6],
       [9, 7, 6, 8, 9]])

In [10]:
arr.shape

(3, 5)

In [11]:
arr.reshape(5,3)

array([[1, 2, 3],
       [4, 5, 2],
       [3, 4, 5],
       [6, 9, 7],
       [6, 8, 9]])

In [12]:
arr.reshape(1,15)

array([[1, 2, 3, 4, 5, 2, 3, 4, 5, 6, 9, 7, 6, 8, 9]])

In [13]:
arr.reshape(3,5)

array([[1, 2, 3, 4, 5],
       [2, 3, 4, 5, 6],
       [9, 7, 6, 8, 9]])

In [21]:
arr[1:2,1:4]

array([[3, 4, 5]])

In [25]:
arr[1:,2:4]

array([[4, 5],
       [6, 8]])

In [27]:
arr_2 = np.arange(0,10,2)
arr_2

array([0, 2, 4, 6, 8])

In [28]:
arr_2 = np.linspace(1,10,50)

In [29]:
arr_2

array([ 1.        ,  1.18367347,  1.36734694,  1.55102041,  1.73469388,
        1.91836735,  2.10204082,  2.28571429,  2.46938776,  2.65306122,
        2.83673469,  3.02040816,  3.20408163,  3.3877551 ,  3.57142857,
        3.75510204,  3.93877551,  4.12244898,  4.30612245,  4.48979592,
        4.67346939,  4.85714286,  5.04081633,  5.2244898 ,  5.40816327,
        5.59183673,  5.7755102 ,  5.95918367,  6.14285714,  6.32653061,
        6.51020408,  6.69387755,  6.87755102,  7.06122449,  7.24489796,
        7.42857143,  7.6122449 ,  7.79591837,  7.97959184,  8.16326531,
        8.34693878,  8.53061224,  8.71428571,  8.89795918,  9.08163265,
        9.26530612,  9.44897959,  9.63265306,  9.81632653, 10.        ])

In [34]:
tst1 = np.arange(0,50)
tst2 = np.linspace(0,10,50)

arr_tst = np.array([tst1, tst2])
arr_tst

array([[ 0.        ,  1.        ,  2.        ,  3.        ,  4.        ,
         5.        ,  6.        ,  7.        ,  8.        ,  9.        ,
        10.        , 11.        , 12.        , 13.        , 14.        ,
        15.        , 16.        , 17.        , 18.        , 19.        ,
        20.        , 21.        , 22.        , 23.        , 24.        ,
        25.        , 26.        , 27.        , 28.        , 29.        ,
        30.        , 31.        , 32.        , 33.        , 34.        ,
        35.        , 36.        , 37.        , 38.        , 39.        ,
        40.        , 41.        , 42.        , 43.        , 44.        ,
        45.        , 46.        , 47.        , 48.        , 49.        ],
       [ 0.        ,  0.20408163,  0.40816327,  0.6122449 ,  0.81632653,
         1.02040816,  1.2244898 ,  1.42857143,  1.63265306,  1.83673469,
         2.04081633,  2.24489796,  2.44897959,  2.65306122,  2.85714286,
         3.06122449,  3.26530612,  3.46938776,  3.

In [36]:
array_tst1 = np.array([1,2,3,4,5])

In [38]:
array_tst1

array([1, 2, 3, 4, 5])

In [41]:
array_tst1[array_tst1 < 4]

array([1, 2, 3])

In [43]:
np.arange(0,10).reshape(5,2)

array([[0, 1],
       [2, 3],
       [4, 5],
       [6, 7],
       [8, 9]])

In [44]:
np.ones(6, dtype=int)

array([1, 1, 1, 1, 1, 1])

In [45]:
np.random.rand(4,4)

array([[0.84302467, 0.80147261, 0.6219855 , 0.43778202],
       [0.01703326, 0.53821428, 0.38551891, 0.13675885],
       [0.8222208 , 0.01096881, 0.72613456, 0.64562179],
       [0.96214528, 0.38883265, 0.70588277, 0.97118827]])

In [46]:
np.random.randn(4,4)

array([[ 0.5434653 , -0.03201241,  0.02059808,  0.14213642],
       [ 0.93685076, -1.71079898, -0.43843242, -0.62828763],
       [-1.44650587,  1.45316649, -0.5536848 ,  1.36173138],
       [-0.20228444,  0.53900309,  2.57124212,  0.32385745]])

In [48]:
np.random.randint(6,60, size=[3,4])

array([[54, 48, 45,  6],
       [30, 53, 39, 37],
       [ 6, 22, 10, 54]])

In [49]:
np.random.randint(0,200,10).reshape(5,2)

array([[121,  56],
       [ 86,  55],
       [ 79,  35],
       [  9,   8],
       [ 86, 120]])